// Client-safe schema - removed database dependencies
// Only keeping sample data and utility functions

// Sample Users Data
export const SAMPLE_USERS = [
  {
    id: 1,
    username: "admin",
    email: "passosmir4@gmail.com",
    userType: "admin" as const,
    tokens: 999999,
    plan: "max" as const,
    credits: 999999,
    maxCredits: 999999,
    highScore: 1500,
    adminLevel: 3,
    documentsStatus: "approved" as const,
    canMakePurchases: true,
    suspended: false,
    banned: false,
    termsAccepted: true,
    tokensPlano: 999999,
    tokensGanhos: 999999,
    tokensComprados: 999999,
    tokensUsados: 0,
    creditosAcumulados: 999999,
    creditosSacados: 0,
    saqueDisponivel: 999999,
    notificacaoSaque: true,
    freePlanAiSearches: 999,
    freePlanPlanetViews: 999,
    freePlanProfileViews: 999,
    freePlanMessages: 999,
    pixPago: 0,
    galaxyVault: 0,
    name: "Admin",
    createdAt: new Date()
  },
  {
    id: 2,
    username: "pedro",
    email: "phpg69@gmail.com",
    userType: "client" as const,
    tokens: 2160,
    plan: "free" as const,
    credits: 20,
    maxCredits: 20,
    highScore: 450,
    adminLevel: 0,
    documentsStatus: "approved" as const,
    canMakePurchases: true,
    suspended: false,
    banned: false,
    termsAccepted: true,
    tokensPlano: 0,
    tokensGanhos: 2160,
    tokensComprados: 0,
    tokensUsados: 0,
    creditosAcumulados: 2160,
    creditosSacados: 0,
    saqueDisponivel: 0,
    notificacaoSaque: true,
    freePlanAiSearches: 10,
    freePlanPlanetViews: 2,
    freePlanProfileViews: 1,
    freePlanMessages: 2,
    pixPago: 6,
    galaxyVault: 0,
    name: "Maria",
    createdAt: new Date()
  },
  {
    id: 3,
    username: "maria",
    email: "mariahelenaearp@gmail.com",
    userType: "client" as const,
    tokens: 4320,
    plan: "free" as const,
    credits: 20,
    maxCredits: 20,
    highScore: 380,
    adminLevel: 0,
    documentsStatus: "approved" as const,
    canMakePurchases: true,
    suspended: false,
    banned: false,
    termsAccepted: true,
    tokensPlano: 0,
    tokensGanhos: 4320,
    tokensComprados: 0,
    tokensUsados: 0,
    creditosAcumulados: 4320,
    creditosSacados: 0,
    saqueDisponivel: 0,
    notificacaoSaque: true,
    freePlanAiSearches: 10,
    freePlanPlanetViews: 2,
    freePlanProfileViews: 1,
    freePlanMessages: 2
  },
  {
    id: 4,
    username: "joao",
    email: "joao.vidal@remederi.com",
    userType: "client" as const,
    tokens: 23040,
    plan: "max" as const,
    credits: 20,
    maxCredits: 20,
    highScore: 720,
    adminLevel: 0,
    documentsStatus: "approved" as const,
    canMakePurchases: true,
    suspended: false,
    banned: false,
    termsAccepted: true,
    tokensPlano: 23040,
    tokensGanhos: 0,
    tokensComprados: 23040,
    tokensUsados: 0,
    creditosAcumulados: 23040,
    creditosSacados: 0,
    saqueDisponivel: 0,
    notificacaoSaque: true,
    freePlanAiSearches: 999,
    freePlanPlanetViews: 999,
    freePlanProfileViews: 999,
    freePlanMessages: 999,
    pixPago: 32,
    galaxyVault: 0,
    name: "João",
    createdAt: new Date()
  }
];

// Sample Professionals Data
export const SAMPLE_PROFESSIONALS = [
  {
    id: 100,
    userId: 100,
    name: "Maria Silva",
    title: "Advogada",
    description: "Especialista em direito civil e trabalhista com 15 anos de experiência.",
    skills: ["Direito Civil", "Direito Trabalhista", "Contratos", "Mediação"],
    services: ["Direito Civil", "Direito Trabalhista", "Contratos", "Mediação"],
    servicesPricing: [1500, 1500, 2000, 1800],
    city: "São Paulo",
    state: "SP",
    rating: 4.8,
    reviewCount: 127,
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 1,
    orbitPosition: 1,
    available: true,
    workRadius: 25,
    latitude: -23.5505,
    longitude: -46.6333,
    hourlyRate: 150,
    verified: true,
    experience: "15 anos",
    education: "Universidade de São Paulo",
    certifications: ["OAB", "Mediadora Judicial"],
    languages: ["Português", "Inglês"],
    specialties: ["Direito Civil", "Direito Trabalhista"],
    portfolio: ["Contrato de locação", "Processo trabalhista", "Mediação familiar"],
    availability: {
      monday: { morning: true, afternoon: true, evening: false },
      tuesday: { morning: true, afternoon: true, evening: false },
      wednesday: { morning: true, afternoon: true, evening: false },
      thursday: { morning: true, afternoon: true, evening: false },
      friday: { morning: true, afternoon: true, evening: false },
      saturday: { morning: false, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 101,
    userId: 101,
    name: "João Santos",
    title: "Eletricista",
    description: "Eletricista profissional com especialização em instalações residenciais e comerciais.",
    skills: ["Instalação Elétrica", "Manutenção", "Automação", "Segurança"],
    services: ["Instalação Elétrica", "Manutenção", "Automação", "Segurança"],
    city: "Rio de Janeiro",
    state: "RJ",
    rating: 4.7,
    reviewCount: 89,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 1,
    orbitPosition: 2,
    available: true,
    workRadius: 30,
    latitude: -22.9068,
    longitude: -43.1729,
    hourlyRate: 80,
    verified: true,
    experience: "12 anos",
    education: "SENAI",
    certifications: ["CREA", "NR-10"],
    languages: ["Português"],
    specialties: ["Instalação Residencial", "Instalação Comercial"],
    portfolio: ["Instalação completa residencial", "Sistema de iluminação LED", "Quadro de distribuição"],
    availability: {
      monday: { morning: true, afternoon: true, evening: true },
      tuesday: { morning: true, afternoon: true, evening: true },
      wednesday: { morning: true, afternoon: true, evening: true },
      thursday: { morning: true, afternoon: true, evening: true },
      friday: { morning: true, afternoon: true, evening: true },
      saturday: { morning: true, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 102,
    userId: 102,
    name: "Ana Costa",
    title: "Designer Gráfico",
    description: "Designer criativa especializada em branding e identidade visual para empresas.",
    skills: ["Branding", "Logo Design", "UI/UX", "Ilustração"],
    services: ["Branding", "Logo Design", "UI/UX", "Ilustração"],
    city: "Belo Horizonte",
    state: "MG",
    rating: 4.9,
    reviewCount: 156,
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 1,
    orbitPosition: 3,
    available: true,
    workRadius: 20,
    latitude: -19.9167,
    longitude: -43.9345,
    hourlyRate: 120,
    verified: true,
    experience: "8 anos",
    education: "Universidade Federal de Minas Gerais",
    certifications: ["Adobe Certified Expert"],
    languages: ["Português", "Inglês"],
    specialties: ["Branding", "Identidade Visual"],
    portfolio: ["Logo para startup tech", "Identidade visual restaurante", "App mobile design"],
    availability: {
      monday: { morning: true, afternoon: true, evening: false },
      tuesday: { morning: true, afternoon: true, evening: false },
      wednesday: { morning: true, afternoon: true, evening: false },
      thursday: { morning: true, afternoon: true, evening: false },
      friday: { morning: true, afternoon: true, evening: false },
      saturday: { morning: false, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 103,
    userId: 103,
    name: "Carlos Oliveira",
    title: "Encanador",
    description: "Encanador experiente com foco em manutenção preventiva e reparos emergenciais.",
    skills: ["Manutenção Hidráulica", "Reparos", "Instalação", "Detecção de Vazamentos"],
    city: "Salvador",
    state: "BA",
    rating: 4.6,
    reviewCount: 73,
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 2,
    orbitPosition: 1,
    available: true,
    workRadius: 35,
    latitude: -12.9714,
    longitude: -38.5011,
    hourlyRate: 70,
    verified: true,
    experience: "18 anos",
    education: "Escola Técnica",
    certifications: ["CREA"],
    languages: ["Português"],
    specialties: ["Manutenção Hidráulica", "Reparos Emergenciais"],
    portfolio: ["Reparo vazamento emergencial", "Instalação sistema hidráulico", "Manutenção preventiva"],
    availability: {
      monday: { morning: true, afternoon: true, evening: true },
      tuesday: { morning: true, afternoon: true, evening: true },
      wednesday: { morning: true, afternoon: true, evening: true },
      thursday: { morning: true, afternoon: true, evening: true },
      friday: { morning: true, afternoon: true, evening: true },
      saturday: { morning: true, afternoon: true, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 104,
    userId: 104,
    name: "Fernanda Lima",
    title: "Psicóloga",
    description: "Psicóloga clínica especializada em terapia cognitivo-comportamental.",
    skills: ["TCC", "Terapia Individual", "Terapia de Casal", "Ansiedade"],
    city: "Brasília",
    state: "DF",
    rating: 4.8,
    reviewCount: 94,
    avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 2,
    orbitPosition: 2,
    available: true,
    workRadius: 15,
    latitude: -15.7942,
    longitude: -47.8822,
    hourlyRate: 200,
    verified: true,
    experience: "10 anos",
    education: "Universidade de Brasília",
    certifications: ["CRP", "Especialização em TCC"],
    languages: ["Português", "Inglês"],
    specialties: ["Terapia Cognitivo-Comportamental", "Ansiedade e Depressão"],
    portfolio: ["Terapia individual", "Terapia de casal", "Grupo de apoio"],
    availability: {
      monday: { morning: true, afternoon: true, evening: false },
      tuesday: { morning: true, afternoon: true, evening: false },
      wednesday: { morning: true, afternoon: true, evening: false },
      thursday: { morning: true, afternoon: true, evening: false },
      friday: { morning: true, afternoon: false, evening: false },
      saturday: { morning: false, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 105,
    userId: 105,
    name: "Roberto Almeida",
    title: "Mecânico",
    description: "Mecânico automotivo especializado em motores e sistemas elétricos.",
    skills: ["Motor", "Sistema Elétrico", "Suspensão", "Freios"],
    city: "Porto Alegre",
    state: "RS",
    rating: 4.5,
    reviewCount: 112,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 2,
    orbitPosition: 3,
    available: true,
    workRadius: 40,
    latitude: -30.0346,
    longitude: -51.2177,
    hourlyRate: 90,
    verified: true,
    experience: "14 anos",
    education: "SENAI",
    certifications: ["CREA"],
    languages: ["Português"],
    specialties: ["Mecânica Automotiva", "Sistemas Elétricos"],
    portfolio: ["Reparo motor", "Sistema elétrico", "Suspensão"],
    availability: {
      monday: { morning: true, afternoon: true, evening: false },
      tuesday: { morning: true, afternoon: true, evening: false },
      wednesday: { morning: true, afternoon: true, evening: false },
      thursday: { morning: true, afternoon: true, evening: false },
      friday: { morning: true, afternoon: true, evening: false },
      saturday: { morning: true, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 106,
    userId: 106,
    name: "Patrícia Souza",
    title: "Dentista",
    description: "Dentista especializada em ortodontia e estética dental.",
    skills: ["Ortodontia", "Estética Dental", "Implantes", "Clareamento"],
    city: "Curitiba",
    state: "PR",
    rating: 4.9,
    reviewCount: 203,
    avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 3,
    orbitPosition: 1,
    available: true,
    workRadius: 25,
    latitude: -25.4289,
    longitude: -49.2671,
    hourlyRate: 300,
    verified: true,
    experience: "12 anos",
    education: "Universidade Federal do Paraná",
    certifications: ["CRO", "Especialização em Ortodontia"],
    languages: ["Português", "Inglês"],
    specialties: ["Ortodontia", "Estética Dental"],
    portfolio: ["Aparelho ortodôntico", "Clareamento dental", "Implante"],
    availability: {
      monday: { morning: true, afternoon: true, evening: false },
      tuesday: { morning: true, afternoon: true, evening: false },
      wednesday: { morning: true, afternoon: true, evening: false },
      thursday: { morning: true, afternoon: true, evening: false },
      friday: { morning: true, afternoon: true, evening: false },
      saturday: { morning: true, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 107,
    userId: 107,
    name: "Lucas Mendes",
    title: "Programador",
    description: "Desenvolvedor full-stack especializado em React, Node.js e Python.",
    skills: ["React", "Node.js", "Python", "TypeScript"],
    city: "Recife",
    state: "PE",
    rating: 4.7,
    reviewCount: 87,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 3,
    orbitPosition: 2,
    available: true,
    workRadius: 30,
    latitude: -8.0476,
    longitude: -34.8770,
    hourlyRate: 150,
    verified: true,
    experience: "6 anos",
    education: "Universidade Federal de Pernambuco",
    certifications: ["AWS Certified Developer"],
    languages: ["Português", "Inglês"],
    specialties: ["Desenvolvimento Web", "Aplicações Mobile"],
    portfolio: ["E-commerce React", "API Node.js", "App mobile React Native"],
    availability: {
      monday: { morning: true, afternoon: true, evening: true },
      tuesday: { morning: true, afternoon: true, evening: true },
      wednesday: { morning: true, afternoon: true, evening: true },
      thursday: { morning: true, afternoon: true, evening: true },
      friday: { morning: true, afternoon: true, evening: true },
      saturday: { morning: false, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 108,
    userId: 108,
    name: "Camila Ferreira",
    title: "Fisioterapeuta",
    description: "Fisioterapeuta especializada em reabilitação esportiva e ortopédica.",
    skills: ["Reabilitação Esportiva", "Ortopedia", "Pilates", "Acupuntura"],
    city: "Fortaleza",
    state: "CE",
    rating: 4.6,
    reviewCount: 134,
    avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 3,
    orbitPosition: 3,
    available: true,
    workRadius: 20,
    latitude: -3.7319,
    longitude: -38.5267,
    hourlyRate: 120,
    verified: true,
    experience: "9 anos",
    education: "Universidade Federal do Ceará",
    certifications: ["CREFITO", "Pilates", "Acupuntura"],
    languages: ["Português"],
    specialties: ["Reabilitação Esportiva", "Fisioterapia Ortopédica"],
    portfolio: ["Reabilitação atleta", "Tratamento coluna", "Pilates terapêutico"],
    availability: {
      monday: { morning: true, afternoon: true, evening: false },
      tuesday: { morning: true, afternoon: true, evening: false },
      wednesday: { morning: true, afternoon: true, evening: false },
      thursday: { morning: true, afternoon: true, evening: false },
      friday: { morning: true, afternoon: true, evening: false },
      saturday: { morning: true, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 109,
    userId: 109,
    name: "Ricardo Costa",
    title: "Arquiteto",
    description: "Arquiteto especializado em projetos residenciais e sustentabilidade.",
    skills: ["Projeto Residencial", "Sustentabilidade", "Interiores", "3D"],
    city: "Goiânia",
    state: "GO",
    rating: 4.8,
    reviewCount: 76,
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 3,
    orbitPosition: 4,
    available: true,
    workRadius: 35,
    latitude: -16.6864,
    longitude: -49.2653,
    hourlyRate: 180,
    verified: true,
    experience: "11 anos",
    education: "Universidade Federal de Goiás",
    certifications: ["CAU", "LEED Green Associate"],
    languages: ["Português", "Inglês"],
    specialties: ["Arquitetura Residencial", "Sustentabilidade"],
    portfolio: ["Casa sustentável", "Reforma apartamento", "Projeto comercial"],
    availability: {
      monday: { morning: true, afternoon: true, evening: false },
      tuesday: { morning: true, afternoon: true, evening: false },
      wednesday: { morning: true, afternoon: true, evening: false },
      thursday: { morning: true, afternoon: true, evening: false },
      friday: { morning: true, afternoon: true, evening: false },
      saturday: { morning: false, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 110,
    userId: 110,
    name: "Juliana Santos",
    title: "Nutricionista",
    description: "Nutricionista especializada em emagrecimento e nutrição esportiva.",
    skills: ["Emagrecimento", "Nutrição Esportiva", "Consultoria", "Planos Alimentares"],
    city: "Manaus",
    state: "AM",
    rating: 4.7,
    reviewCount: 98,
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 3,
    orbitPosition: 5,
    available: true,
    workRadius: 25,
    latitude: -3.1190,
    longitude: -60.0217,
    hourlyRate: 100,
    verified: true,
    experience: "7 anos",
    education: "Universidade Federal do Amazonas",
    certifications: ["CRN", "Nutrição Esportiva"],
    languages: ["Português"],
    specialties: ["Nutrição Clínica", "Nutrição Esportiva"],
    portfolio: ["Plano emagrecimento", "Nutrição atleta", "Consultoria empresa"],
    availability: {
      monday: { morning: true, afternoon: true, evening: false },
      tuesday: { morning: true, afternoon: true, evening: false },
      wednesday: { morning: true, afternoon: true, evening: false },
      thursday: { morning: true, afternoon: true, evening: false },
      friday: { morning: true, afternoon: true, evening: false },
      saturday: { morning: true, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 111,
    userId: 111,
    name: "Marcelo Silva",
    title: "Personal Trainer",
    description: "Personal trainer especializado em musculação e treinamento funcional.",
    skills: ["Musculação", "Treinamento Funcional", "Aeróbico", "Nutrição Esportiva"],
    city: "Vitória",
    state: "ES",
    rating: 4.5,
    reviewCount: 145,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 3,
    orbitPosition: 6,
    available: true,
    workRadius: 30,
    latitude: -20.2976,
    longitude: -40.2958,
    hourlyRate: 80,
    verified: true,
    experience: "8 anos",
    education: "Universidade Federal do Espírito Santo",
    certifications: ["CREF", "Personal Trainer"],
    languages: ["Português"],
    specialties: ["Musculação", "Treinamento Funcional"],
    portfolio: ["Treino emagrecimento", "Hipertrofia", "Treino funcional"],
    availability: {
      monday: { morning: true, afternoon: true, evening: true },
      tuesday: { morning: true, afternoon: true, evening: true },
      wednesday: { morning: true, afternoon: true, evening: true },
      thursday: { morning: true, afternoon: true, evening: true },
      friday: { morning: true, afternoon: true, evening: true },
      saturday: { morning: true, afternoon: true, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 112,
    userId: 112,
    name: "Amanda Costa",
    title: "Fotógrafa",
    description: "Fotógrafa profissional especializada em eventos e retratos.",
    skills: ["Eventos", "Retratos", "Edição", "Vídeo"],
    city: "Campo Grande",
    state: "MS",
    rating: 4.8,
    reviewCount: 67,
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 3,
    orbitPosition: 7,
    available: true,
    workRadius: 40,
    latitude: -20.4486,
    longitude: -54.6295,
    hourlyRate: 200,
    verified: true,
    experience: "5 anos",
    education: "Universidade Federal de Mato Grosso do Sul",
    certifications: ["Fotografia Profissional"],
    languages: ["Português", "Inglês"],
    specialties: ["Fotografia de Eventos", "Retratos"],
    portfolio: ["Casamento", "Ensaio fotográfico", "Evento corporativo"],
    availability: {
      monday: { morning: true, afternoon: true, evening: true },
      tuesday: { morning: true, afternoon: true, evening: true },
      wednesday: { morning: true, afternoon: true, evening: true },
      thursday: { morning: true, afternoon: true, evening: true },
      friday: { morning: true, afternoon: true, evening: true },
      saturday: { morning: true, afternoon: true, evening: true },
      sunday: { morning: true, afternoon: true, evening: false }
    }
  },
  {
    id: 113,
    userId: 113,
    name: "Diego Oliveira",
    title: "Pintor",
    description: "Pintor profissional especializado em pintura residencial e comercial.",
    skills: ["Pintura Residencial", "Pintura Comercial", "Texturas", "Acabamentos"],
    city: "Cuiabá",
    state: "MT",
    rating: 4.4,
    reviewCount: 89,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 3,
    orbitPosition: 8,
    available: true,
    workRadius: 35,
    latitude: -15.6010,
    longitude: -56.0974,
    hourlyRate: 60,
    verified: true,
    experience: "16 anos",
    education: "Escola Técnica",
    certifications: ["Pintor Profissional"],
    languages: ["Português"],
    specialties: ["Pintura Residencial", "Pintura Comercial"],
    portfolio: ["Pintura casa", "Pintura escritório", "Textura decorativa"],
    availability: {
      monday: { morning: true, afternoon: true, evening: false },
      tuesday: { morning: true, afternoon: true, evening: false },
      wednesday: { morning: true, afternoon: true, evening: false },
      thursday: { morning: true, afternoon: true, evening: false },
      friday: { morning: true, afternoon: true, evening: false },
      saturday: { morning: true, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 114,
    userId: 114,
    name: "Vanessa Lima",
    title: "Consultora de Marketing",
    description: "Consultora de marketing digital especializada em redes sociais e SEO.",
    skills: ["Marketing Digital", "Redes Sociais", "SEO", "Google Ads"],
    city: "Palmas",
    state: "TO",
    rating: 4.6,
    reviewCount: 56,
    avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 3,
    orbitPosition: 9,
    available: true,
    workRadius: 20,
    latitude: -10.1753,
    longitude: -48.2982,
    hourlyRate: 120,
    verified: true,
    experience: "6 anos",
    education: "Universidade Federal do Tocantins",
    certifications: ["Google Ads", "Facebook Ads"],
    languages: ["Português", "Inglês"],
    specialties: ["Marketing Digital", "Gestão de Redes Sociais"],
    portfolio: ["Campanha Google Ads", "Gestão Instagram", "SEO website"],
    availability: {
      monday: { morning: true, afternoon: true, evening: false },
      tuesday: { morning: true, afternoon: true, evening: false },
      wednesday: { morning: true, afternoon: true, evening: false },
      thursday: { morning: true, afternoon: true, evening: false },
      friday: { morning: true, afternoon: true, evening: false },
      saturday: { morning: false, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 115,
    userId: 115,
    name: "Thiago Martins",
    title: "Técnico de Informática",
    description: "Técnico especializado em manutenção de computadores e redes.",
    skills: ["Manutenção PC", "Redes", "Recuperação de Dados", "Instalação Software"],
    city: "Aracaju",
    state: "SE",
    rating: 4.3,
    reviewCount: 78,
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 3,
    orbitPosition: 10,
    available: true,
    workRadius: 30,
    latitude: -10.9091,
    longitude: -37.0677,
    hourlyRate: 70,
    verified: true,
    experience: "10 anos",
    education: "Escola Técnica",
    certifications: ["CompTIA A+"],
    languages: ["Português"],
    specialties: ["Manutenção de Computadores", "Redes"],
    portfolio: ["Manutenção PC", "Configuração rede", "Recuperação dados"],
    availability: {
      monday: { morning: true, afternoon: true, evening: true },
      tuesday: { morning: true, afternoon: true, evening: true },
      wednesday: { morning: true, afternoon: true, evening: true },
      thursday: { morning: true, afternoon: true, evening: true },
      friday: { morning: true, afternoon: true, evening: true },
      saturday: { morning: true, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 116,
    userId: 116,
    name: "Larissa Santos",
    title: "Veterinária",
    description: "Veterinária especializada em pequenos animais e emergências.",
    skills: ["Pequenos Animais", "Emergências", "Vacinação", "Cirurgia"],
    city: "João Pessoa",
    state: "PB",
    rating: 4.7,
    reviewCount: 92,
    avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 3,
    orbitPosition: 11,
    available: true,
    workRadius: 25,
    latitude: -7.1150,
    longitude: -34.8631,
    hourlyRate: 150,
    verified: true,
    experience: "8 anos",
    education: "Universidade Federal da Paraíba",
    certifications: ["CRMV", "Especialização em Pequenos Animais"],
    languages: ["Português"],
    specialties: ["Medicina Veterinária", "Pequenos Animais"],
    portfolio: ["Consulta cão", "Vacinação gato", "Emergência"],
    availability: {
      monday: { morning: true, afternoon: true, evening: true },
      tuesday: { morning: true, afternoon: true, evening: true },
      wednesday: { morning: true, afternoon: true, evening: true },
      thursday: { morning: true, afternoon: true, evening: true },
      friday: { morning: true, afternoon: true, evening: true },
      saturday: { morning: true, afternoon: true, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 117,
    userId: 117,
    name: "Rafael Costa",
    title: "Jardinheiro",
    description: "Jardinheiro profissional especializado em paisagismo e manutenção.",
    skills: ["Paisagismo", "Manutenção", "Poda", "Irrigação"],
    city: "Teresina",
    state: "PI",
    rating: 4.4,
    reviewCount: 45,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 3,
    orbitPosition: 12,
    available: true,
    workRadius: 40,
    latitude: -5.0892,
    longitude: -42.8016,
    hourlyRate: 50,
    verified: true,
    experience: "12 anos",
    education: "Escola Técnica",
    certifications: ["Jardinagem Profissional"],
    languages: ["Português"],
    specialties: ["Paisagismo", "Manutenção de Jardins"],
    portfolio: ["Jardim residencial", "Paisagismo comercial", "Manutenção"],
    availability: {
      monday: { morning: true, afternoon: true, evening: false },
      tuesday: { morning: true, afternoon: true, evening: false },
      wednesday: { morning: true, afternoon: true, evening: false },
      thursday: { morning: true, afternoon: true, evening: false },
      friday: { morning: true, afternoon: true, evening: false },
      saturday: { morning: true, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 118,
    userId: 118,
    name: "Carolina Alves",
    title: "Professora de Inglês",
    description: "Professora de inglês com metodologia personalizada para todos os níveis.",
    skills: ["Inglês", "Conversação", "Gramática", "Preparação TOEFL"],
    city: "Natal",
    state: "RN",
    rating: 4.8,
    reviewCount: 123,
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 3,
    orbitPosition: 13,
    available: true,
    workRadius: 20,
    latitude: -5.7945,
    longitude: -35.2090,
    hourlyRate: 80,
    verified: true,
    experience: "9 anos",
    education: "Universidade Federal do Rio Grande do Norte",
    certifications: ["CELTA", "TOEFL"],
    languages: ["Português", "Inglês"],
    specialties: ["Inglês Conversacional", "Preparação para Exames"],
    portfolio: ["Aula conversação", "Preparação TOEFL", "Inglês business"],
    availability: {
      monday: { morning: true, afternoon: true, evening: true },
      tuesday: { morning: true, afternoon: true, evening: true },
      wednesday: { morning: true, afternoon: true, evening: true },
      thursday: { morning: true, afternoon: true, evening: true },
      friday: { morning: true, afternoon: true, evening: true },
      saturday: { morning: true, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 119,
    userId: 119,
    name: "Bruno Silva",
    title: "Mestre de Obras",
    description: "Mestre de obras especializado em construção civil e reformas.",
    skills: ["Construção Civil", "Reformas", "Gerenciamento", "Orçamentos"],
    city: "Maceió",
    state: "AL",
    rating: 4.5,
    reviewCount: 67,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 3,
    orbitPosition: 14,
    available: true,
    workRadius: 35,
    latitude: -9.6498,
    longitude: -35.7089,
    hourlyRate: 100,
    verified: true,
    experience: "20 anos",
    education: "Escola Técnica",
    certifications: ["CREA"],
    languages: ["Português"],
    specialties: ["Construção Civil", "Reformas"],
    portfolio: ["Construção casa", "Reforma apartamento", "Obra comercial"],
    availability: {
      monday: { morning: true, afternoon: true, evening: false },
      tuesday: { morning: true, afternoon: true, evening: false },
      wednesday: { morning: true, afternoon: true, evening: false },
      thursday: { morning: true, afternoon: true, evening: false },
      friday: { morning: true, afternoon: true, evening: false },
      saturday: { morning: true, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  }
];

// Token Packages
export const TOKEN_PACKAGES = [
  {
    id: "starter",
    name: "Starter Pack",
    price: 3,
    baseTokens: 1800,
    bonusTokens: 600,
    totalTokens: 2400,
    icon: "coins"
  },
  {
    id: "pro",
    name: "Pro Boost",
    price: 6,
    baseTokens: 3600,
    bonusTokens: 1650,
    totalTokens: 5250,
    icon: "zap"
  },
  {
    id: "max",
    name: "Max Expansion",
    price: 9,
    baseTokens: 5400,
    bonusTokens: 2600,
    totalTokens: 8000,
    icon: "star",
    popular: true
  },
  {
    id: "premium",
    name: "Orbit Premium",
    price: 18,
    baseTokens: 10800,
    bonusTokens: 5700,
    totalTokens: 16500,
    icon: "sparkles"
  },
  {
    id: "galaxy",
    name: "Galaxy Vault",
    price: 31,
    baseTokens: 18600,
    bonusTokens: 9650,
    totalTokens: 28250,
    icon: "crown"
  }
];

// Utility Functions
export const formatCurrency = (value: number): string => {
  return new Intl.NumberFormat('pt-BR', {
    style: 'currency',
    currency: 'BRL'
  }).format(value);
};

export const formatTokens = (tokens: number): string => {
  return new Intl.NumberFormat('pt-BR').format(tokens);
};

export const getTotalTokens = (user: any): number => {
  return (user.tokensPlano || 0) + (user.tokensGanhos || 0) + (user.tokensComprados || 0) - (user.tokensUsados || 0);
};

// Types for client use
export type User = typeof SAMPLE_USERS[0];
export type Professional = typeof SAMPLE_PROFESSIONALS[0];
export type TokenPackage = typeof TOKEN_PACKAGES[0]; 