// import { pgTable, text, varchar, serial, integer, boolean, real, timestamp } from "drizzle-orm/pg-core";
// import { createInsertSchema } from "drizzle-zod";
// import { z } from "zod";

// Dados mock para desenvolvimento - sem dependências de banco
export const SAMPLE_USERS = [
  {
    id: 1,
    username: "admin",
    email: "passosmir4@gmail.com",
    userType: "admin",
    tokens: 999999,
    plan: "max",
    fullName: "Administrador",
    phone: "+55 11 99999-9999",
    profilePhoto: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    pixKey: "admin@orbitrum.com",
    pixKeyValidated: true,
    termsAccepted: true,
    termsAcceptedAt: new Date(),
    credits: 999999,
    maxCredits: 999999,
    gamesPlayedToday: 0,
    highScore: 0,
    tokensPlano: 999999,
    tokensGanhos: 999999,
    tokensComprados: 999999,
    tokensUsados: 0,
    creditosAcumulados: 999999,
    creditosSacados: 0,
    saqueDisponivel: 999999,
    notificacaoSaque: true,
    adminLevel: 3,
    adminPermissions: ["all"],
    documentsStatus: "approved",
    canMakePurchases: true,
    suspended: false,
    banned: false,
    isPromotionalUser: false,
    referralCount: 0,
    freePlanAiSearches: 999,
    freePlanPlanetViews: 999,
    freePlanProfileViews: 999,
    freePlanMessages: 999
  },
  {
    id: 2,
    username: "cliente_demo",
    email: "cliente@demo.com",
    userType: "client",
    tokens: 150,
    plan: "free",
    fullName: "Cliente Demo",
    phone: "+55 11 88888-8888",
    profilePhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    pixKey: "cliente@demo.com",
    pixKeyValidated: false,
    termsAccepted: true,
    termsAcceptedAt: new Date(),
    credits: 20,
    maxCredits: 20,
    gamesPlayedToday: 0,
    highScore: 0,
    tokensPlano: 0,
    tokensGanhos: 20,
    tokensComprados: 0,
    tokensUsados: 0,
    creditosAcumulados: 20,
    creditosSacados: 0,
    saqueDisponivel: 0,
    notificacaoSaque: true,
    adminLevel: 0,
    adminPermissions: [],
    documentsStatus: "pending",
    canMakePurchases: false,
    suspended: false,
    banned: false,
    isPromotionalUser: false,
    referralCount: 0,
    freePlanAiSearches: 10,
    freePlanPlanetViews: 2,
    freePlanProfileViews: 1,
    freePlanMessages: 2
  }
];

export const SAMPLE_PROFESSIONALS = [
  {
    id: 100,
    userId: 100,
    name: "Maria Silva",
    title: "Advogada Especialista em Direito Civil",
    description: "Advogada com mais de 10 anos de experiência em direito civil, trabalhista e previdenciário. Especializada em contratos, divórcios e questões trabalhistas.",
    skills: ["Direito Civil", "Direito Trabalhista", "Contratos", "Divórcio", "Direito Previdenciário"],
    city: "São Paulo",
    state: "SP",
    available: true,
    rating: 4.8,
    reviewCount: 45,
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 1,
    orbitPosition: 1,
    latitude: -23.5505,
    longitude: -46.6333,
    workRadius: 25,
    hourlyRate: 150,
    verified: true,
    experience: "10+ anos",
    education: "Direito - USP",
    languages: ["Português", "Inglês"],
    specializations: ["Direito Civil", "Direito Trabalhista"],
    availability: {
      monday: { morning: true, afternoon: true, evening: false },
      tuesday: { morning: true, afternoon: true, evening: false },
      wednesday: { morning: true, afternoon: true, evening: false },
      thursday: { morning: true, afternoon: true, evening: false },
      friday: { morning: true, afternoon: true, evening: false },
      saturday: { morning: false, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 101,
    userId: 101,
    name: "João Santos",
    title: "Eletricista Residencial e Industrial",
    description: "Eletricista profissional com certificação e experiência em instalações residenciais e industriais. Trabalho com segurança e garantia.",
    skills: ["Instalação Elétrica", "Manutenção", "Automação", "Painéis Elétricos", "Iluminação"],
    city: "São Paulo",
    state: "SP",
    available: true,
    rating: 4.9,
    reviewCount: 67,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 1,
    orbitPosition: 2,
    latitude: -23.5505,
    longitude: -46.6333,
    workRadius: 30,
    hourlyRate: 80,
    verified: true,
    experience: "8+ anos",
    education: "Técnico em Eletrotécnica",
    languages: ["Português"],
    specializations: ["Instalação Residencial", "Instalação Industrial"],
    availability: {
      monday: { morning: true, afternoon: true, evening: true },
      tuesday: { morning: true, afternoon: true, evening: true },
      wednesday: { morning: true, afternoon: true, evening: true },
      thursday: { morning: true, afternoon: true, evening: true },
      friday: { morning: true, afternoon: true, evening: true },
      saturday: { morning: true, afternoon: true, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 102,
    userId: 102,
    name: "Ana Costa",
    title: "Designer de Interiores",
    description: "Designer de interiores criativa e experiente, especializada em projetos residenciais e comerciais. Transformo espaços com estilo e funcionalidade.",
    skills: ["Design de Interiores", "Projeto Residencial", "Projeto Comercial", "Decoração", "Consultoria"],
    city: "São Paulo",
    state: "SP",
    available: true,
    rating: 4.7,
    reviewCount: 19,
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 3,
    orbitPosition: 5,
    latitude: -23.5505,
    longitude: -46.6333,
    workRadius: 20,
    hourlyRate: 120,
    verified: true,
    experience: "6+ anos",
    education: "Design de Interiores - Belas Artes",
    languages: ["Português", "Inglês"],
    specializations: ["Design Residencial", "Design Comercial"],
    availability: {
      monday: { morning: true, afternoon: true, evening: false },
      tuesday: { morning: true, afternoon: true, evening: false },
      wednesday: { morning: true, afternoon: true, evening: false },
      thursday: { morning: true, afternoon: true, evening: false },
      friday: { morning: true, afternoon: true, evening: false },
      saturday: { morning: true, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 103,
    userId: 103,
    name: "Carlos Oliveira",
    title: "Encanador Profissional",
    description: "Encanador experiente com especialização em hidráulica. Atendo emergências e faço manutenção preventiva em residências e empresas.",
    skills: ["Hidráulica", "Manutenção", "Reparo", "Instalação", "Emergências"],
    city: "São Paulo",
    state: "SP",
    available: true,
    rating: 4.6,
    reviewCount: 34,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 2,
    orbitPosition: 3,
    latitude: -23.5505,
    longitude: -46.6333,
    workRadius: 25,
    hourlyRate: 70,
    verified: true,
    experience: "12+ anos",
    education: "Técnico em Hidráulica",
    languages: ["Português"],
    specializations: ["Hidráulica Residencial", "Hidráulica Industrial"],
    availability: {
      monday: { morning: true, afternoon: true, evening: true },
      tuesday: { morning: true, afternoon: true, evening: true },
      wednesday: { morning: true, afternoon: true, evening: true },
      thursday: { morning: true, afternoon: true, evening: true },
      friday: { morning: true, afternoon: true, evening: true },
      saturday: { morning: true, afternoon: true, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 104,
    userId: 104,
    name: "Fernanda Lima",
    title: "Psicóloga Clínica",
    description: "Psicóloga clínica especializada em terapia cognitivo-comportamental. Atendo adultos, adolescentes e casais.",
    skills: ["Psicologia Clínica", "TCC", "Terapia Individual", "Terapia de Casal", "Ansiedade"],
    city: "São Paulo",
    state: "SP",
    available: true,
    rating: 4.9,
    reviewCount: 28,
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 1,
    orbitPosition: 4,
    latitude: -23.5505,
    longitude: -46.6333,
    workRadius: 15,
    hourlyRate: 200,
    verified: true,
    experience: "7+ anos",
    education: "Psicologia - PUC-SP",
    languages: ["Português", "Inglês"],
    specializations: ["TCC", "Terapia Individual", "Terapia de Casal"],
    availability: {
      monday: { morning: true, afternoon: true, evening: false },
      tuesday: { morning: true, afternoon: true, evening: false },
      wednesday: { morning: true, afternoon: true, evening: false },
      thursday: { morning: true, afternoon: true, evening: false },
      friday: { morning: true, afternoon: true, evening: false },
      saturday: { morning: true, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 105,
    userId: 105,
    name: "Roberto Almeida",
    title: "Personal Trainer",
    description: "Personal trainer certificado com especialização em musculação e funcional. Ajudo a alcançar seus objetivos de forma segura e eficiente.",
    skills: ["Musculação", "Funcional", "Emagrecimento", "Hipertrofia", "Reabilitação"],
    city: "São Paulo",
    state: "SP",
    available: true,
    rating: 4.8,
    reviewCount: 42,
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 2,
    orbitPosition: 1,
    latitude: -23.5505,
    longitude: -46.6333,
    workRadius: 20,
    hourlyRate: 100,
    verified: true,
    experience: "5+ anos",
    education: "Educação Física - UNIFESP",
    languages: ["Português", "Inglês"],
    specializations: ["Musculação", "Funcional", "Emagrecimento"],
    availability: {
      monday: { morning: true, afternoon: true, evening: true },
      tuesday: { morning: true, afternoon: true, evening: true },
      wednesday: { morning: true, afternoon: true, evening: true },
      thursday: { morning: true, afternoon: true, evening: true },
      friday: { morning: true, afternoon: true, evening: true },
      saturday: { morning: true, afternoon: true, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 106,
    userId: 106,
    name: "Patrícia Souza",
    title: "Nutricionista Esportiva",
    description: "Nutricionista especializada em nutrição esportiva e emagrecimento. Elaboro planos alimentares personalizados para seus objetivos.",
    skills: ["Nutrição Esportiva", "Emagrecimento", "Hipertrofia", "Consultoria", "Planos Alimentares"],
    city: "São Paulo",
    state: "SP",
    available: true,
    rating: 4.7,
    reviewCount: 31,
    avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 3,
    orbitPosition: 2,
    latitude: -23.5505,
    longitude: -46.6333,
    workRadius: 18,
    hourlyRate: 150,
    verified: true,
    experience: "6+ anos",
    education: "Nutrição - USP",
    languages: ["Português", "Inglês"],
    specializations: ["Nutrição Esportiva", "Emagrecimento"],
    availability: {
      monday: { morning: true, afternoon: true, evening: false },
      tuesday: { morning: true, afternoon: true, evening: false },
      wednesday: { morning: true, afternoon: true, evening: false },
      thursday: { morning: true, afternoon: true, evening: false },
      friday: { morning: true, afternoon: true, evening: false },
      saturday: { morning: true, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 107,
    userId: 107,
    name: "Marcelo Ferreira",
    title: "Técnico em Informática",
    description: "Técnico em informática com experiência em manutenção de computadores, notebooks e redes. Atendo residências e empresas.",
    skills: ["Manutenção de PC", "Notebooks", "Redes", "Software", "Hardware"],
    city: "São Paulo",
    state: "SP",
    available: true,
    rating: 4.5,
    reviewCount: 56,
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 2,
    orbitPosition: 4,
    latitude: -23.5505,
    longitude: -46.6333,
    workRadius: 30,
    hourlyRate: 90,
    verified: true,
    experience: "9+ anos",
    education: "Técnico em Informática",
    languages: ["Português", "Inglês"],
    specializations: ["Manutenção de PC", "Redes", "Notebooks"],
    availability: {
      monday: { morning: true, afternoon: true, evening: true },
      tuesday: { morning: true, afternoon: true, evening: true },
      wednesday: { morning: true, afternoon: true, evening: true },
      thursday: { morning: true, afternoon: true, evening: true },
      friday: { morning: true, afternoon: true, evening: true },
      saturday: { morning: true, afternoon: true, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 108,
    userId: 108,
    name: "Lucia Mendes",
    title: "Fisioterapeuta",
    description: "Fisioterapeuta especializada em fisioterapia ortopédica e esportiva. Tratamento de lesões e reabilitação funcional.",
    skills: ["Fisioterapia Ortopédica", "Fisioterapia Esportiva", "Reabilitação", "Pilates", "Acupuntura"],
    city: "São Paulo",
    state: "SP",
    available: true,
    rating: 4.8,
    reviewCount: 38,
    avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 1,
    orbitPosition: 5,
    latitude: -23.5505,
    longitude: -46.6333,
    workRadius: 22,
    hourlyRate: 120,
    verified: true,
    experience: "8+ anos",
    education: "Fisioterapia - UNIFESP",
    languages: ["Português", "Inglês"],
    specializations: ["Fisioterapia Ortopédica", "Fisioterapia Esportiva"],
    availability: {
      monday: { morning: true, afternoon: true, evening: false },
      tuesday: { morning: true, afternoon: true, evening: false },
      wednesday: { morning: true, afternoon: true, evening: false },
      thursday: { morning: true, afternoon: true, evening: false },
      friday: { morning: true, afternoon: true, evening: false },
      saturday: { morning: true, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 109,
    userId: 109,
    name: "Ricardo Santos",
    title: "Pintor Profissional",
    description: "Pintor profissional com experiência em pintura residencial e comercial. Trabalho com qualidade e pontualidade.",
    skills: ["Pintura Residencial", "Pintura Comercial", "Texturas", "Acabamentos", "Preparação"],
    city: "São Paulo",
    state: "SP",
    available: true,
    rating: 4.6,
    reviewCount: 29,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 3,
    orbitPosition: 3,
    latitude: -23.5505,
    longitude: -46.6333,
    workRadius: 25,
    hourlyRate: 60,
    verified: true,
    experience: "11+ anos",
    education: "Técnico em Pintura",
    languages: ["Português"],
    specializations: ["Pintura Residencial", "Pintura Comercial"],
    availability: {
      monday: { morning: true, afternoon: true, evening: false },
      tuesday: { morning: true, afternoon: true, evening: false },
      wednesday: { morning: true, afternoon: true, evening: false },
      thursday: { morning: true, afternoon: true, evening: false },
      friday: { morning: true, afternoon: true, evening: false },
      saturday: { morning: true, afternoon: true, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 110,
    userId: 110,
    name: "Camila Rodrigues",
    title: "Dentista",
    description: "Dentista especializada em odontologia estética e restauradora. Atendo com carinho e tecnologia de ponta.",
    skills: ["Odontologia Estética", "Restauração", "Limpeza", "Clareamento", "Ortodontia"],
    city: "São Paulo",
    state: "SP",
    available: true,
    rating: 4.9,
    reviewCount: 47,
    avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 1,
    orbitPosition: 3,
    latitude: -23.5505,
    longitude: -46.6333,
    workRadius: 20,
    hourlyRate: 300,
    verified: true,
    experience: "12+ anos",
    education: "Odontologia - USP",
    languages: ["Português", "Inglês"],
    specializations: ["Odontologia Estética", "Restauração"],
    availability: {
      monday: { morning: true, afternoon: true, evening: false },
      tuesday: { morning: true, afternoon: true, evening: false },
      wednesday: { morning: true, afternoon: true, evening: false },
      thursday: { morning: true, afternoon: true, evening: false },
      friday: { morning: true, afternoon: true, evening: false },
      saturday: { morning: true, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 111,
    userId: 111,
    name: "André Costa",
    title: "Mestre de Obras",
    description: "Mestre de obras com experiência em construção civil e reformas. Coordeno equipes e garanto qualidade na execução.",
    skills: ["Construção Civil", "Reformas", "Coordenação", "Orçamentos", "Fiscalização"],
    city: "São Paulo",
    state: "SP",
    available: true,
    rating: 4.7,
    reviewCount: 33,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 2,
    orbitPosition: 5,
    latitude: -23.5505,
    longitude: -46.6333,
    workRadius: 35,
    hourlyRate: 120,
    verified: true,
    experience: "15+ anos",
    education: "Técnico em Edificações",
    languages: ["Português"],
    specializations: ["Construção Civil", "Reformas"],
    availability: {
      monday: { morning: true, afternoon: true, evening: false },
      tuesday: { morning: true, afternoon: true, evening: false },
      wednesday: { morning: true, afternoon: true, evening: false },
      thursday: { morning: true, afternoon: true, evening: false },
      friday: { morning: true, afternoon: true, evening: false },
      saturday: { morning: true, afternoon: true, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 112,
    userId: 112,
    name: "Juliana Alves",
    title: "Fotógrafa Profissional",
    description: "Fotógrafa especializada em ensaios fotográficos, eventos e fotografia corporativa. Capturo momentos especiais com criatividade.",
    skills: ["Ensaio Fotográfico", "Eventos", "Fotografia Corporativa", "Edição", "Retrato"],
    city: "São Paulo",
    state: "SP",
    available: true,
    rating: 4.8,
    reviewCount: 25,
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 3,
    orbitPosition: 1,
    latitude: -23.5505,
    longitude: -46.6333,
    workRadius: 40,
    hourlyRate: 180,
    verified: true,
    experience: "6+ anos",
    education: "Fotografia - SENAC",
    languages: ["Português", "Inglês"],
    specializations: ["Ensaio Fotográfico", "Eventos", "Corporativa"],
    availability: {
      monday: { morning: true, afternoon: true, evening: true },
      tuesday: { morning: true, afternoon: true, evening: true },
      wednesday: { morning: true, afternoon: true, evening: true },
      thursday: { morning: true, afternoon: true, evening: true },
      friday: { morning: true, afternoon: true, evening: true },
      saturday: { morning: true, afternoon: true, evening: true },
      sunday: { morning: true, afternoon: true, evening: false }
    }
  },
  {
    id: 113,
    userId: 113,
    name: "Pedro Martins",
    title: "Consultor Financeiro",
    description: "Consultor financeiro especializado em planejamento financeiro pessoal e empresarial. Ajudo a organizar e multiplicar seu dinheiro.",
    skills: ["Planejamento Financeiro", "Investimentos", "Consultoria", "Orçamento", "Educação Financeira"],
    city: "São Paulo",
    state: "SP",
    available: true,
    rating: 4.9,
    reviewCount: 41,
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 1,
    orbitPosition: 2,
    latitude: -23.5505,
    longitude: -46.6333,
    workRadius: 30,
    hourlyRate: 250,
    verified: true,
    experience: "10+ anos",
    education: "Administração - FGV",
    languages: ["Português", "Inglês"],
    specializations: ["Planejamento Financeiro", "Investimentos"],
    availability: {
      monday: { morning: true, afternoon: true, evening: false },
      tuesday: { morning: true, afternoon: true, evening: false },
      wednesday: { morning: true, afternoon: true, evening: false },
      thursday: { morning: true, afternoon: true, evening: false },
      friday: { morning: true, afternoon: true, evening: false },
      saturday: { morning: true, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 114,
    userId: 114,
    name: "Tatiana Silva",
    title: "Professora de Inglês",
    description: "Professora de inglês com certificação internacional e experiência em aulas particulares e em grupo. Metodologia personalizada.",
    skills: ["Inglês", "Conversação", "Gramática", "Preparação para Exames", "Business English"],
    city: "São Paulo",
    state: "SP",
    available: true,
    rating: 4.7,
    reviewCount: 36,
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 2,
    orbitPosition: 2,
    latitude: -23.5505,
    longitude: -46.6333,
    workRadius: 25,
    hourlyRate: 80,
    verified: true,
    experience: "8+ anos",
    education: "Letras - USP",
    languages: ["Português", "Inglês", "Espanhol"],
    specializations: ["Conversação", "Business English", "Preparação para Exames"],
    availability: {
      monday: { morning: true, afternoon: true, evening: true },
      tuesday: { morning: true, afternoon: true, evening: true },
      wednesday: { morning: true, afternoon: true, evening: true },
      thursday: { morning: true, afternoon: true, evening: true },
      friday: { morning: true, afternoon: true, evening: true },
      saturday: { morning: true, afternoon: true, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 115,
    userId: 115,
    name: "Gabriel Oliveira",
    title: "Desenvolvedor Web",
    description: "Desenvolvedor web full-stack especializado em React, Node.js e aplicações modernas. Crio soluções digitais inovadoras.",
    skills: ["React", "Node.js", "JavaScript", "TypeScript", "Full-Stack"],
    city: "São Paulo",
    state: "SP",
    available: true,
    rating: 4.8,
    reviewCount: 52,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 1,
    orbitPosition: 1,
    latitude: -23.5505,
    longitude: -46.6333,
    workRadius: 50,
    hourlyRate: 150,
    verified: true,
    experience: "7+ anos",
    education: "Sistemas de Informação - USP",
    languages: ["Português", "Inglês"],
    specializations: ["React", "Node.js", "Full-Stack"],
    availability: {
      monday: { morning: true, afternoon: true, evening: true },
      tuesday: { morning: true, afternoon: true, evening: true },
      wednesday: { morning: true, afternoon: true, evening: true },
      thursday: { morning: true, afternoon: true, evening: true },
      friday: { morning: true, afternoon: true, evening: true },
      saturday: { morning: true, afternoon: true, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 116,
    userId: 116,
    name: "Mariana Costa",
    title: "Arquiteta",
    description: "Arquiteta especializada em projetos residenciais e comerciais. Crio espaços funcionais e esteticamente agradáveis.",
    skills: ["Projetos Residenciais", "Projetos Comerciais", "Interiores", "Maquetes", "3D"],
    city: "São Paulo",
    state: "SP",
    available: true,
    rating: 4.9,
    reviewCount: 29,
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 2,
    orbitPosition: 3,
    latitude: -23.5505,
    longitude: -46.6333,
    workRadius: 35,
    hourlyRate: 200,
    verified: true,
    experience: "9+ anos",
    education: "Arquitetura - FAU-USP",
    languages: ["Português", "Inglês"],
    specializations: ["Projetos Residenciais", "Projetos Comerciais"],
    availability: {
      monday: { morning: true, afternoon: true, evening: false },
      tuesday: { morning: true, afternoon: true, evening: false },
      wednesday: { morning: true, afternoon: true, evening: false },
      thursday: { morning: true, afternoon: true, evening: false },
      friday: { morning: true, afternoon: true, evening: false },
      saturday: { morning: true, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 117,
    userId: 117,
    name: "Rafael Santos",
    title: "Mecânico Automotivo",
    description: "Mecânico automotivo especializado em motores, transmissão e elétrica. Diagnóstico preciso e reparo de qualidade.",
    skills: ["Motores", "Transmissão", "Elétrica", "Diagnóstico", "Manutenção"],
    city: "São Paulo",
    state: "SP",
    available: true,
    rating: 4.6,
    reviewCount: 48,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 3,
    orbitPosition: 4,
    latitude: -23.5505,
    longitude: -46.6333,
    workRadius: 30,
    hourlyRate: 85,
    verified: true,
    experience: "13+ anos",
    education: "Técnico em Mecânica Automotiva",
    languages: ["Português"],
    specializations: ["Motores", "Transmissão", "Elétrica"],
    availability: {
      monday: { morning: true, afternoon: true, evening: true },
      tuesday: { morning: true, afternoon: true, evening: true },
      wednesday: { morning: true, afternoon: true, evening: true },
      thursday: { morning: true, afternoon: true, evening: true },
      friday: { morning: true, afternoon: true, evening: true },
      saturday: { morning: true, afternoon: true, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 118,
    userId: 118,
    name: "Isabela Ferreira",
    title: "Designer Gráfico",
    description: "Designer gráfico criativo especializado em identidade visual, logos e material promocional. Crio designs que impactam.",
    skills: ["Identidade Visual", "Logos", "Material Promocional", "Social Media", "Ilustração"],
    city: "São Paulo",
    state: "SP",
    available: true,
    rating: 4.7,
    reviewCount: 34,
    avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 2,
    orbitPosition: 4,
    latitude: -23.5505,
    longitude: -46.6333,
    workRadius: 40,
    hourlyRate: 120,
    verified: true,
    experience: "5+ anos",
    education: "Design Gráfico - Belas Artes",
    languages: ["Português", "Inglês"],
    specializations: ["Identidade Visual", "Logos", "Social Media"],
    availability: {
      monday: { morning: true, afternoon: true, evening: true },
      tuesday: { morning: true, afternoon: true, evening: true },
      wednesday: { morning: true, afternoon: true, evening: true },
      thursday: { morning: true, afternoon: true, evening: true },
      friday: { morning: true, afternoon: true, evening: true },
      saturday: { morning: true, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  },
  {
    id: 119,
    userId: 119,
    name: "Thiago Lima",
    title: "Advogado Trabalhista",
    description: "Advogado especializado em direito trabalhista e previdenciário. Defendo seus direitos com ética e competência.",
    skills: ["Direito Trabalhista", "Direito Previdenciário", "Recursos", "Consultoria", "Acordos"],
    city: "São Paulo",
    state: "SP",
    available: true,
    rating: 4.8,
    reviewCount: 39,
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    orbitRing: 1,
    orbitPosition: 6,
    latitude: -23.5505,
    longitude: -46.6333,
    workRadius: 25,
    hourlyRate: 180,
    verified: true,
    experience: "11+ anos",
    education: "Direito - PUC-SP",
    languages: ["Português", "Inglês"],
    specializations: ["Direito Trabalhista", "Direito Previdenciário"],
    availability: {
      monday: { morning: true, afternoon: true, evening: false },
      tuesday: { morning: true, afternoon: true, evening: false },
      wednesday: { morning: true, afternoon: true, evening: false },
      thursday: { morning: true, afternoon: true, evening: false },
      friday: { morning: true, afternoon: true, evening: false },
      saturday: { morning: true, afternoon: false, evening: false },
      sunday: { morning: false, afternoon: false, evening: false }
    }
  }
];

// Pacotes de tokens para a loja
export const TOKEN_PACKAGES = [
  {
    id: "starter",
    name: "Starter Pack",
    price: 3,
    baseTokens: 1800,
    bonusTokens: 600,
    totalTokens: 2400,
    icon: "coins"
  },
  {
    id: "pro",
    name: "Pro Boost",
    price: 6,
    baseTokens: 3600,
    bonusTokens: 1650,
    totalTokens: 5250,
    icon: "zap"
  },
  {
    id: "max",
    name: "Max Expansion",
    price: 9,
    baseTokens: 5400,
    bonusTokens: 2600,
    totalTokens: 8000,
    icon: "star",
    popular: true
  },
  {
    id: "premium",
    name: "Orbit Premium",
    price: 18,
    baseTokens: 10800,
    bonusTokens: 5700,
    totalTokens: 16500,
    icon: "sparkles"
  },
  {
    id: "galaxy",
    name: "Galaxy Vault",
    price: 31,
    baseTokens: 18600,
    bonusTokens: 9650,
    totalTokens: 28250,
    icon: "crown"
  }
];

// Função para calcular tokens totais
export const getTotalTokens = (user: any): number => {
  return (user.tokensPlano || 0) + (user.tokensGanhos || 0) + (user.tokensComprados || 0) - (user.tokensUsados || 0);
}; 